### ISSUE TITLE
Is it possible to speed up rent+ ?

### ISSUE THREAD

**Issue by WeiCSong** [mdedge/rhps_coalescent#1]
Hi,
    I'm trying to use your code to estimate prs trajectory for GWAS, and I found that the rent+ on a single loci took nearly one hour, which means that analyzing all 1700 locus would take 1700 core-hour. I'm wondering whether we can speed up this procedure, e.g. using other faster coalescent tools or narrowing the window size (currently it is 100000)?  Thank you very much for you help.

Best
Weichen Song

**Comment by edgepopgen** [comment]
Hi, thanks for the question! You can certainly narrow the window size; whether that is a good idea will depend on the level of linkage in the species you're looking at. As long as the trees you're including are correlated with the focal tree, including them might help RENT+ estimate the focal tree.

There are faster tools for estimating ARGs available since we wrote the paper, Relate (Speidel et al) and tsInfer (Kelleher et al). By default, tsInfer does not include branch length information, but there is an add-on tool that can estimate them. These are faster to run, but it'll require a bit of extra work to sort out the formatting and get these tools to run.

**Comment by WeiCSong** [comment]
Thanks for the suggestion! I'm studying RELATE these days and I found that their detectselection module gives estimated allele frequency for each SNP at each generation. I assume that we can directly calculate PRS using this frequency, without the need of proportion-of-lineage estimation, is that right? If so, is it reasonable to apply your Tx test on the frequency matrix (SNP as rows and generations as columns), as you applied to the trajs_neut matrix? 

Thank you very much for your help :)

**Comment by edgepopgen** [comment]
I'm not sure how that RELATE module computes their estimated allele frequencies, but yes, in principle it seems like it'd be a reasonable thing to use their frequencies, compute PRS from them, and then test with Tx.

**Comment by WeiCSong** [comment]
Got it, thanks!
